import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const BUILTIN_RECIPES = [
  {id:'r1',name:'番茄牛肉意面',image:'assets/images/tomato-beef-pasta.svg',category:'主食',time:25,difficulty:'简单',builtin:true,ingredients:[['牛肉',300,'g','肉蛋'],['意大利面',200,'g','主食'],['番茄',3,'个','蔬菜'],['洋葱',0.5,'个','蔬菜'],['橄榄油',15,'ml','调味料']],steps:['番茄切块、洋葱切丝，牛肉切薄片。','意大利面按包装时间煮熟，保留少量面汤。','锅中倒油，炒香洋葱和牛肉，再加入番茄炒出汁。','加入意面和少量面汤翻匀，按口味调味即可。']},
  {id:'r2',name:'香煎鸡胸配西兰花',image:'assets/images/chicken-broccoli.svg',category:'高蛋白',time:20,difficulty:'简单',builtin:true,ingredients:[['鸡胸肉',400,'g','肉蛋'],['西兰花',1,'个','蔬菜'],['黑胡椒',3,'g','调味料'],['橄榄油',10,'ml','调味料']],steps:['鸡胸肉用黑胡椒和少量盐腌制10分钟。','西兰花焯水2分钟。','平底锅少油，中火将鸡胸两面煎熟。','搭配西兰花装盘即可。']},
  {id:'r3',name:'鸡蛋蔬菜早餐卷',image:'assets/images/breakfast-wrap.svg',category:'早餐',time:15,difficulty:'简单',builtin:true,ingredients:[['鸡蛋',2,'个','肉蛋'],['全麦饼',1,'个','主食'],['生菜',60,'g','蔬菜'],['番茄',1,'个','蔬菜']],steps:['鸡蛋打散后炒熟。','全麦饼稍微加热。','铺上生菜、番茄和鸡蛋。','卷起后对半切开。']},
  {id:'r4',name:'奶油蘑菇浓汤',image:'assets/images/mushroom-soup.svg',category:'汤',time:30,difficulty:'中等',builtin:true,ingredients:[['蘑菇',250,'g','蔬菜'],['牛奶',300,'ml','乳制品'],['洋葱',0.5,'个','蔬菜'],['黄油',15,'g','乳制品']],steps:['蘑菇和洋葱切片。','黄油炒香洋葱，再加入蘑菇。','倒入牛奶，小火煮10分钟。','用料理机打至顺滑后再加热调味。']},
  {id:'r5',name:'三文鱼牛油果饭',image:'assets/images/salmon-avocado.svg',category:'高蛋白',time:25,difficulty:'中等',builtin:true,ingredients:[['三文鱼',220,'g','肉蛋'],['大米',150,'g','主食'],['牛油果',1,'个','水果'],['黄瓜',120,'g','蔬菜']],steps:['米饭提前煮好。','三文鱼煎熟或烤熟。','牛油果、黄瓜切片。','所有食材铺在米饭上即可。']},
  {id:'r6',name:'酸奶水果燕麦杯',image:'assets/images/yogurt-oats.svg',category:'早餐',time:8,difficulty:'简单',builtin:true,ingredients:[['酸奶',200,'g','乳制品'],['燕麦',50,'g','主食'],['香蕉',1,'个','水果'],['蓝莓',80,'g','水果']],steps:['杯底铺一层燕麦。','加入一层酸奶。','铺上香蕉片和蓝莓。','重复分层后即可食用。']}
];
const days=['周一','周二','周三','周四','周五','周六','周日'];const mealSlots=['早餐','午餐','晚餐'];
const defaultPlan={'周一':{早餐:'r6',午餐:'r1',晚餐:'r2'},'周二':{早餐:'r3',午餐:'r5',晚餐:'r4'},'周三':{早餐:'r6',午餐:null,晚餐:'r2'},'周四':{早餐:'r3',午餐:'r1',晚餐:null},'周五':{早餐:'r6',午餐:'r5',晚餐:'r4'},'周六':{早餐:null,午餐:null,晚餐:'r1'},'周日':{早餐:'r3',午餐:null,晚餐:'r2'}};
const defaultPantry=[{id:'p1',name:'意大利面',amount:500,unit:'g',category:'主食',expiry:''},{id:'p2',name:'鸡蛋',amount:6,unit:'个',category:'肉蛋',expiry:''},{id:'p3',name:'牛奶',amount:1000,unit:'ml',category:'乳制品',expiry:''},{id:'p4',name:'番茄',amount:2,unit:'个',category:'蔬菜',expiry:''}];
const defaultState=()=>({plan:structuredClone(defaultPlan),pantry:structuredClone(defaultPantry),checked:{},manualShopping:[],favorites:['r1','r2','r6']});
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state=JSON.parse(localStorage.getItem('shiguang-v2-state')||'null')||defaultState();let customRecipes=[];let recipes=[...BUILTIN_RECIPES];let activeDay='周一';let pickerContext=null;let currentUser=null;let syncTimer=null;let authMode='login';
const cfg=window.SHIGUANG_CONFIG||{};const cloudConfigured=Boolean(cfg.SUPABASE_URL&&cfg.SUPABASE_PUBLISHABLE_KEY);const supabase=cloudConfigured?createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;

function clone(v){return JSON.parse(JSON.stringify(v))}function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1900)}
function recipeById(id){return recipes.find(r=>r.id===id)}function normalizeAmount(v,u){if(u==='kg')return[v*1000,'g'];if(u==='L')return[v*1000,'ml'];return[v,u]}function formatAmount(v,u){return`${Number.isInteger(v)?v:Math.round(v*10)/10} ${u}`}
function catEmoji(cat){return({'肉蛋':'🥩','蔬菜':'🥬','水果':'🍎','乳制品':'🥛','主食':'🍚','调味料':'🧂','其他':'🛒'})[cat]||'🛒'}
function saveLocal(){localStorage.setItem('shiguang-v2-state',JSON.stringify(state));}
function markSync(text,online=false){$('#syncText').textContent=text;$('#syncDot').classList.toggle('online',online);$('#cloudPill').classList.toggle('online',online);$('#cloudPill').textContent=online?'云端已连接':'本机体验'}
async function persist(){saveLocal();if(!currentUser||!supabase)return;clearTimeout(syncTimer);syncTimer=setTimeout(async()=>{markSync('正在同步…',true);const payload={user_id:currentUser.id,plan:state.plan,pantry:state.pantry,checked:state.checked,manual_shopping:state.manualShopping,favorites:state.favorites,updated_at:new Date().toISOString()};const{error}=await supabase.from('app_state').upsert(payload,{onConflict:'user_id'});markSync(error?'同步失败，已保存在本机':'已同步到云端',!error);if(error)toast('云端同步失败，请检查 Supabase 配置');},350)}
async function loadCloudState(){if(!currentUser||!supabase)return;markSync('正在读取云端数据…',true);const{data,error}=await supabase.from('app_state').select('*').eq('user_id',currentUser.id).maybeSingle();if(error){toast('读取云端数据失败');markSync('云端读取失败',false);return}if(data){state={plan:data.plan||clone(defaultPlan),pantry:data.pantry||[],checked:data.checked||{},manualShopping:data.manual_shopping||[],favorites:data.favorites||[]};saveLocal()}else{await persist()}await loadCustomRecipes();markSync('已同步到云端',true);renderAll()}
async function signedImage(path){if(!path||!supabase)return'assets/images/recipe-placeholder.svg';const{data,error}=await supabase.storage.from('recipe-images').createSignedUrl(path,3600);return error?'assets/images/recipe-placeholder.svg':data.signedUrl}
async function loadCustomRecipes(){if(!currentUser||!supabase){customRecipes=[];recipes=[...BUILTIN_RECIPES];return}const{data,error}=await supabase.from('recipes').select('*').order('created_at',{ascending:false});if(error){toast('自定义食谱加载失败');return}customRecipes=await Promise.all((data||[]).map(async r=>({id:r.id,name:r.name,category:r.category,time:r.cook_time,difficulty:r.difficulty,ingredients:r.ingredients||[],steps:r.steps||[],image:await signedImage(r.image_path),imagePath:r.image_path,builtin:false})));recipes=[...customRecipes,...BUILTIN_RECIPES]}
function route(){const id=(location.hash||'#home').slice(1);const page=$(`#${id}`)||$('#home');$$('.page').forEach(p=>p.classList.remove('active'));page.classList.add('active');$$('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${page.id}`));$('#nav').classList.remove('open');renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const today=state.plan['周一'];$('#todayMeals').innerHTML=mealSlots.map(slot=>{const r=recipeById(today?.[slot]);return`<article class="card meal-card">${r?`<img class="thumb" src="${r.image}" alt="${r.name}"><div class="content"><span class="meal-label">${slot}</span><h3>${r.name}</h3><div class="meal-meta">${r.time} min · ${r.difficulty}</div></div>`:`<div class="content"><span class="meal-label">${slot}</span><h3>还没安排</h3><div class="meal-meta">去本周菜单添加一道菜</div></div>`}</article>`}).join('');$('#pantryCount').textContent=state.pantry.length;$('#favoriteCount').textContent=state.favorites.length;$('#shoppingCount').textContent=buildShoppingList().length}
function renderWeekTabs(){$('#weekTabs').innerHTML=days.map(d=>`<button class="${d===activeDay?'active':''}" data-day="${d}">${d}</button>`).join('');$$('#weekTabs button').forEach(b=>b.onclick=()=>{activeDay=b.dataset.day;renderWeekTabs();renderMealPlan()})}
function renderMealPlan(){$('#mealPlanGrid').innerHTML=mealSlots.map(slot=>{const id=state.plan?.[activeDay]?.[slot],r=recipeById(id);return r?`<article class="card plan-card"><img class="plan-thumb" src="${r.image}" alt="${r.name}"><div class="plan-bottom"><span class="slot">${activeDay} · ${slot}</span><h3>${r.name}</h3><div class="meal-meta">${r.time} min · ${r.difficulty}</div><div class="plan-actions"><button class="btn ghost choose" data-slot="${slot}">更换</button><button class="btn danger remove" data-slot="${slot}">移除</button></div></div></article>`:`<article class="card empty-plan"><div><div class="plus">＋</div><h3>添加${slot}</h3><button class="btn primary choose" data-slot="${slot}">选择食谱</button></div></article>`}).join('');$$('.choose').forEach(b=>b.onclick=()=>openPicker(activeDay,b.dataset.slot));$$('.remove').forEach(b=>b.onclick=async()=>{state.plan[activeDay][b.dataset.slot]=null;await persist();renderAll()})}
function renderRecipeFilters(){const cats=['全部',...new Set(recipes.map(r=>r.category))];const current=$('#recipeFilters').dataset.current||'全部';$('#recipeFilters').innerHTML=cats.map(c=>`<button class="${c===current?'active':''}" data-cat="${c}">${c}</button>`).join('');$$('#recipeFilters button').forEach(b=>b.onclick=()=>{$('#recipeFilters').dataset.current=b.dataset.cat;renderRecipeFilters();renderRecipes()})}
function renderRecipes(){const q=$('#recipeSearch').value.trim().toLowerCase(),cat=$('#recipeFilters').dataset.current||'全部';const data=recipes.filter(r=>(cat==='全部'||r.category===cat)&&(!q||r.name.toLowerCase().includes(q)||(r.ingredients||[]).some(i=>String(i[0]).includes(q))));$('#recipeGrid').innerHTML=data.map(r=>`<article class="card recipe-card"><div class="recipe-cover"><img src="${r.image}" alt="${r.name}">${!r.builtin?'<span class="user-badge">我的食谱</span>':''}<button class="favorite-btn" data-fav="${r.id}">${state.favorites.includes(r.id)?'♥':'♡'}</button></div><div class="recipe-body"><h3>${r.name}</h3><div class="recipe-tags"><span class="tag">${r.category}</span><span class="tag">${r.difficulty}</span></div><div class="recipe-footer"><span>⏱ ${r.time} min</span><button class="link" data-open="${r.id}">查看食谱 →</button></div></div></article>`).join('')||'<div class="card empty">没有找到匹配的食谱。</div>';$$('[data-open]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.open));$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)})}
async function toggleFav(id){const i=state.favorites.indexOf(id);i>=0?state.favorites.splice(i,1):state.favorites.push(id);await persist();renderAll()}
function openRecipe(id){const r=recipeById(id);if(!r)return;$('#recipeDialogContent').innerHTML=`<div class="dialog-hero"><img src="${r.image}" alt="${r.name}"><div class="dialog-title-overlay"><span class="eyebrow">${r.category}</span><h2>${r.name}</h2><div>⏱ ${r.time} 分钟 · ${r.difficulty}</div></div></div><div class="dialog-body"><h3>食材</h3><div class="ingredients">${(r.ingredients||[]).map(i=>`<div class="ingredient"><b>${i[0]}</b><br><span class="meal-meta">${formatAmount(Number(i[1]),i[2])}</span></div>`).join('')}</div><h3>做法</h3><ol class="steps">${(r.steps||[]).map(s=>`<li>${s}</li>`).join('')}</ol><div class="dialog-actions"><button class="btn primary" id="addRecipeToPlan">加入本周菜单</button><button class="btn ghost" id="dialogFav">${state.favorites.includes(id)?'取消收藏':'收藏食谱'}</button>${!r.builtin?'<button class="btn danger" id="deleteCustomRecipe">删除食谱</button>':''}</div></div>`;$('#addRecipeToPlan').onclick=()=>{$('#recipeDialog').close();openPicker('周一','晚餐',id)};$('#dialogFav').onclick=async()=>{await toggleFav(id);openRecipe(id)};if(!r.builtin)$('#deleteCustomRecipe').onclick=()=>deleteCustomRecipe(r);$('#recipeDialog').showModal()}
function openPicker(day,slot,presetId=null){pickerContext={day,slot,presetId};$('#miniRecipeList').innerHTML=recipes.map(r=>`<div class="mini-recipe"><img src="${r.image}" alt=""><div><h4>${r.name}</h4><p>${r.category} · ${r.time} min</p></div><button class="btn ${r.id===presetId?'primary':'ghost'}" data-pick="${r.id}">选择</button></div>`).join('');$$('[data-pick]').forEach(b=>b.onclick=async()=>{state.plan[pickerContext.day][pickerContext.slot]=b.dataset.pick;await persist();$('#mealPickerDialog').close();toast(`已加入 ${pickerContext.day} ${pickerContext.slot}`);renderAll()});$('#mealPickerDialog').showModal()}
function pantryMap(){const map={};for(const p of state.pantry){const[v,u]=normalizeAmount(Number(p.amount),p.unit);const key=`${p.name}|${u}`;map[key]=(map[key]||0)+v}return map}
function buildShoppingList(){const needed=new Map();for(const day of days)for(const slot of mealSlots){const r=recipeById(state.plan?.[day]?.[slot]);if(!r)continue;(r.ingredients||[]).forEach(([name,amount,unit,category])=>{const[v,u]=normalizeAmount(Number(amount),unit);const k=`${name}|${u}|${category}`;needed.set(k,(needed.get(k)||0)+v)})}const pantry=pantryMap(),list=[];for(const[k,amount]of needed){const[name,unit,category]=k.split('|'),left=Math.max(0,amount-(pantry[`${name}|${unit}`]||0));if(left>0)list.push({id:`auto:${name}:${unit}`,name,amount:left,unit,category,manual:false})}state.manualShopping.forEach(m=>list.push({...m,manual:true}));return list}
function renderShopping(){const list=buildShoppingList(),groups={};list.forEach(i=>(groups[i.category||'其他']??=[]).push(i));$('#shoppingGroups').innerHTML=Object.keys(groups).length?Object.entries(groups).map(([cat,items])=>`<section class="card shopping-group"><h3>${catEmoji(cat)} ${cat}</h3>${items.map(i=>{const checked=!!state.checked[i.id];return`<div class="shopping-item ${checked?'checked':''}"><input type="checkbox" data-check="${i.id}" ${checked?'checked':''}><div class="item-name">${i.name}</div><div class="qty">${i.manual?i.qtyText:formatAmount(i.amount,i.unit)}</div>${i.manual?`<button class="icon-btn" data-del-manual="${i.id}">×</button>`:''}</div>`}).join('')}</section>`).join(''):'<div class="card empty">采购清单已经空啦 🎉</div>';$$('[data-check]').forEach(c=>c.onchange=async()=>{state.checked[c.dataset.check]=c.checked;await persist();renderShopping();renderHome()});$$('[data-del-manual]').forEach(b=>b.onclick=async()=>{state.manualShopping=state.manualShopping.filter(x=>x.id!==b.dataset.delManual);delete state.checked[b.dataset.delManual];await persist();renderAll()});const done=list.filter(i=>state.checked[i.id]).length;$('#shoppingProgressText').textContent=`${done} / ${list.length}`;$('#shoppingProgressBar').style.width=list.length?`${done/list.length*100}%`:'0%'}
function renderPantry(){$('#pantryGrid').innerHTML=state.pantry.map(p=>{let soon=false,label='未设置保质期';if(p.expiry){const daysLeft=Math.ceil((new Date(p.expiry)-new Date())/86400000);soon=daysLeft<=3;label=daysLeft<0?'已过期':`${daysLeft} 天后到期`}return`<article class="card pantry-card"><div class="pantry-card-head"><div><span class="tag">${catEmoji(p.category)} ${p.category}</span><h3>${p.name}</h3></div><button class="icon-btn" data-del-pantry="${p.id}">×</button></div><div class="pantry-amount">${p.amount} <span class="meal-meta">${p.unit}</span></div><div class="expiry ${soon?'soon':''}">📅 ${label}</div></article>`}).join('')||'<div class="card empty">冰箱还是空的，添加一些库存吧。</div>';$$('[data-del-pantry]').forEach(b=>b.onclick=async()=>{state.pantry=state.pantry.filter(p=>p.id!==b.dataset.delPantry);await persist();renderAll()})}
function renderAll(){renderHome();renderWeekTabs();renderMealPlan();renderRecipeFilters();renderRecipes();renderShopping();renderPantry();renderAccountStatus()}
function renderAccountStatus(){if(currentUser){$('#cloudPill').textContent='云端已连接';$('#cloudPill').classList.add('online');$('#accountBtn').textContent='✓';markSync('已登录，同步到云端',true)}else{$('#accountBtn').textContent='👤';if(!cloudConfigured)markSync('当前为本机体验模式',false);else markSync('登录后开启跨设备同步',false)}}
function renderAccountDialog(){const panel=$('#accountPanel');if(!cloudConfigured){panel.innerHTML=`<span class="eyebrow">CLOUD SETUP</span><h2>开启云端同步</h2><p>第二版已经支持 Supabase，但你还没有填写云端项目配置。</p><div class="account-info"><b>现在网页仍然可以体验</b><span>数据暂时保存在当前浏览器。部署前按照 README 的步骤填写 config.js，即可开启登录与同步。</span></div><button class="btn primary" id="closeSetup">知道了</button>`;$('#closeSetup').onclick=()=>$('#accountDialog').close();return}if(currentUser){panel.innerHTML=`<span class="eyebrow">ACCOUNT</span><h2>云端账户</h2><p>这个账号的数据会在手机和电脑之间同步。</p><div class="account-info"><b>${currentUser.email||'已登录用户'}</b><span>用户 ID：${currentUser.id.slice(0,8)}…</span></div><button class="btn danger" id="logoutBtn">退出登录</button>`;$('#logoutBtn').onclick=logout;return}panel.innerHTML=`<span class="eyebrow">WELCOME BACK</span><h2>${authMode==='login'?'登录食光':'创建食光账号'}</h2><p>使用同一个账号登录不同设备，即可看到同一份菜单、库存和采购数据。</p><div class="auth-tabs"><button id="tabLogin" class="${authMode==='login'?'active':''}">登录</button><button id="tabSignup" class="${authMode==='signup'?'active':''}">注册</button></div><form class="auth-form" id="authForm"><label>邮箱<input id="authEmail" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>密码<input id="authPassword" type="password" minlength="6" autocomplete="${authMode==='login'?'current-password':'new-password'}" required placeholder="至少 6 位"></label><button class="btn primary" type="submit">${authMode==='login'?'登录':'注册'}</button><div class="auth-help">注册后如果项目开启了邮箱确认，请到邮箱点击确认链接后再登录。</div></form>`;$('#tabLogin').onclick=()=>{authMode='login';renderAccountDialog()};$('#tabSignup').onclick=()=>{authMode='signup';renderAccountDialog()};$('#authForm').onsubmit=handleAuth}
async function handleAuth(e){e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const btn=e.submitter;btn.disabled=true;btn.textContent='处理中…';if(authMode==='signup'){const{data,error}=await supabase.auth.signUp({email,password});if(error){toast(error.message)}else if(data.session){toast('注册成功，已登录')}else{toast('注册成功，请检查邮箱完成确认')}}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)toast(error.message);else toast('登录成功')}btn.disabled=false;renderAccountDialog()}
async function logout(){await supabase.auth.signOut();currentUser=null;customRecipes=[];recipes=[...BUILTIN_RECIPES];state=JSON.parse(localStorage.getItem('shiguang-v2-state')||'null')||defaultState();renderAll();$('#accountDialog').close();toast('已退出云端账户')}
async function initAuth(){if(!supabase){renderAccountStatus();return}const{data}=await supabase.auth.getSession();currentUser=data.session?.user||null;if(currentUser)await loadCloudState();supabase.auth.onAuthStateChange(async(_event,session)=>{const prev=currentUser?.id;currentUser=session?.user||null;if(currentUser&&currentUser.id!==prev){$('#accountDialog').close();await loadCloudState()}if(!currentUser&&prev){customRecipes=[];recipes=[...BUILTIN_RECIPES];renderAll()}renderAccountStatus()})}
function parseIngredients(text){return text.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split(',').map(x=>x.trim());if(p.length<4)throw new Error(`食材格式不正确：${line}`);return[p[0],Number(p[1]),p[2],p[3]]})}
async function createCustomRecipe(e){e.preventDefault();if(!currentUser||!supabase){toast('请先登录云端账户再新增跨设备食谱');$('#accountDialog').showModal();renderAccountDialog();return}const btn=$('#saveRecipeBtn');btn.disabled=true;btn.textContent='正在保存…';try{const name=$('#newRecipeName').value.trim(),category=$('#newRecipeCategory').value,cook_time=Number($('#newRecipeTime').value),difficulty=$('#newRecipeDifficulty').value,ingredients=parseIngredients($('#newRecipeIngredients').value),steps=$('#newRecipeSteps').value.split('\n').map(x=>x.trim()).filter(Boolean);let image_path=null;const file=$('#newRecipeImage').files[0];if(file){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase();image_path=`${currentUser.id}/${crypto.randomUUID()}.${ext}`;const{error:upErr}=await supabase.storage.from('recipe-images').upload(image_path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(upErr)throw upErr}const{error}=await supabase.from('recipes').insert({user_id:currentUser.id,name,category,cook_time,difficulty,ingredients,steps,image_path});if(error)throw error;await loadCustomRecipes();$('#newRecipeDialog').close();e.target.reset();renderAll();toast('食谱已保存到云端')}catch(err){toast(err.message||'保存失败')}finally{btn.disabled=false;btn.textContent='保存食谱'}}
async function deleteCustomRecipe(r){if(!currentUser||!supabase)return;if(!confirm(`确定删除“${r.name}”吗？`))return;const{error}=await supabase.from('recipes').delete().eq('id',r.id);if(error){toast('删除失败');return}if(r.imagePath)await supabase.storage.from('recipe-images').remove([r.imagePath]);for(const d of days)for(const s of mealSlots)if(state.plan[d][s]===r.id)state.plan[d][s]=null;state.favorites=state.favorites.filter(x=>x!==r.id);await persist();await loadCustomRecipes();$('#recipeDialog').close();renderAll();toast('已删除食谱')}

$('#recipeSearch').addEventListener('input',renderRecipes);$('#mobileNav').onclick=()=>$('#nav').classList.toggle('open');$('#dialogClose').onclick=()=>$('#recipeDialog').close();$('#pickerClose').onclick=()=>$('#mealPickerDialog').close();$('#accountClose').onclick=()=>$('#accountDialog').close();$('#newRecipeClose').onclick=()=>$('#newRecipeDialog').close();$('#accountBtn').onclick=()=>{$('#accountDialog').showModal();renderAccountDialog()};$('#newRecipeBtn').onclick=()=>{if(!currentUser){$('#accountDialog').showModal();renderAccountDialog();if(cloudConfigured)toast('登录后可把新食谱和图片保存到云端');return}$('#newRecipeDialog').showModal()};$('#newRecipeForm').onsubmit=createCustomRecipe;
$('#generateShoppingBtn').onclick=()=>{renderShopping();location.hash='shopping';toast('采购清单已根据本周菜单更新')};$('#clearCheckedBtn').onclick=async()=>{const checkedIds=new Set(Object.keys(state.checked).filter(k=>state.checked[k]));state.manualShopping=state.manualShopping.filter(i=>!checkedIds.has(i.id));checkedIds.forEach(k=>delete state.checked[k]);await persist();renderAll();toast('已清除已购买项目')};$('#quickAddForm').onsubmit=async e=>{e.preventDefault();state.manualShopping.push({id:`manual:${Date.now()}`,name:$('#quickAddName').value.trim(),qtyText:$('#quickAddQty').value.trim(),category:'其他'});e.target.reset();await persist();renderAll();toast('已加入采购清单')};$('#pantryForm').onsubmit=async e=>{e.preventDefault();state.pantry.push({id:`p:${Date.now()}`,name:$('#pantryName').value.trim(),amount:Number($('#pantryAmount').value),unit:$('#pantryUnit').value,category:$('#pantryCategory').value,expiry:$('#pantryExpiry').value});e.target.reset();await persist();renderAll();toast('已加入冰箱库存')};$('#randomMealBtn').onclick=async()=>{const picks=[...recipes].sort(()=>Math.random()-.5).slice(0,3);const labels=['早餐','午餐','晚餐'];picks.forEach((r,i)=>state.plan['周一'][labels[i]]=r.id);await persist();renderAll();toast('已经随机生成一套今日菜单 ✨')};
window.addEventListener('hashchange',route);window.addEventListener('online',()=>{if(currentUser)loadCloudState()});window.addEventListener('offline',()=>markSync('网络已断开，修改暂存于本机',false));
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(!location.hash)location.hash='#home';else route();renderAll();initAuth();
