const VERSION='1.1.000';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const MEALS=[['早餐','07:30','sunrise'],['午餐','12:30','sun'],['晚餐','19:00','moon']];
const WEEK=['周日','周一','周二','周三','周四','周五','周六'];
const BUILTINS={
 r1:{id:'r1',name:'番茄牛肉意面',image:'assets/images/tomato-beef-pasta.svg',category:'主食',time:25,difficulty:'简单',ingredients:[['牛肉',300,'g','肉蛋'],['意大利面',200,'g','主食'],['番茄',3,'个','蔬菜'],['洋葱',.5,'个','蔬菜'],['橄榄油',15,'ml','调味料']]},
 r2:{id:'r2',name:'香煎鸡胸配西兰花',image:'assets/images/chicken-broccoli.svg',category:'高蛋白',time:20,difficulty:'简单',ingredients:[['鸡胸肉',400,'g','肉蛋'],['西兰花',1,'个','蔬菜'],['黑胡椒',3,'g','调味料'],['橄榄油',10,'ml','调味料']]},
 r3:{id:'r3',name:'鸡蛋蔬菜早餐卷',image:'assets/images/breakfast-wrap.svg',category:'早餐',time:15,difficulty:'简单',ingredients:[['鸡蛋',2,'个','肉蛋'],['全麦饼',1,'个','主食'],['生菜',60,'g','蔬菜'],['番茄',1,'个','蔬菜']]},
 r4:{id:'r4',name:'奶油蘑菇浓汤',image:'assets/images/mushroom-soup.svg',category:'汤',time:30,difficulty:'中等',ingredients:[['蘑菇',250,'g','蔬菜'],['牛奶',300,'ml','乳制品'],['洋葱',.5,'个','蔬菜'],['黄油',15,'g','乳制品']]},
 r5:{id:'r5',name:'三文鱼牛油果饭',image:'assets/images/salmon-avocado.svg',category:'高蛋白',time:25,difficulty:'中等',ingredients:[['三文鱼',220,'g','肉蛋'],['大米',150,'g','主食'],['牛油果',1,'个','水果'],['黄瓜',120,'g','蔬菜']]},
 r6:{id:'r6',name:'酸奶水果燕麦杯',image:'assets/images/yogurt-oats.svg',category:'早餐',time:8,difficulty:'简单',ingredients:[['酸奶',200,'g','乳制品'],['燕麦',50,'g','主食'],['香蕉',1,'个','水果'],['蓝莓',80,'g','水果']]}
};
const state={recipes:{...BUILTINS},groups:[],members:[],dishes:[],remoteAt:0,profile:null,user:null,lastLocal:''};
const ICONS={
 home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
 utensils:'<path d="M3 2v7a3 3 0 0 0 6 0V2M6 2v20M15 2v8c0 2 1.5 3 3 3h1V2M18 13v9"/>',book:'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/>',cart:'<circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l2.7 11h10.8l2-7H7"/>',package:'<path d="m21 8-9 5-9-5 9-5 9 5Z"/><path d="m3 8 9 5 9-5M12 13v9"/>',fridge:'<rect x="5" y="2" width="14" height="20" rx="2"/><path d="M5 10h14M8 6v2M8 14v3"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.2.35.48.64.82.84.34.2.73.3 1.12.3H21v4h-.1a1.7 1.7 0 0 0-1.5.86Z"/>',
 search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',bell:'<path d="M18 8a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',plus:'<path d="M12 5v14M5 12h14"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',check:'<path d="m5 12 4 4L19 6"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',sunrise:'<path d="M4 18h16M6 14a6 6 0 0 1 12 0M12 2v4M4.9 6.9l2.8 2.8M19.1 6.9l-2.8 2.8"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/>',moon:'<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>'
};
function svg(name,cls=''){return`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name]||ICONS.utensils}</svg>`;}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function localState(){try{return JSON.parse(localStorage.getItem('shiguang-v2-state')||'{}')||{}}catch{return{}}}
function dayKey(date=new Date()){return WEEK[date.getDay()]}
function iso(date=new Date()){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function prettyDate(date=new Date()){return`${date.getMonth()+1}月${date.getDate()}日 ${WEEK[date.getDay()]}`}
function normalize(v,u){v=Number(v)||0;if(u==='kg')return[v*1000,'g'];if(u==='L')return[v*1000,'ml'];return[v,u]}
function fmt(v,u){const n=Math.round(Number(v)*10)/10;return`${Number.isInteger(n)?n:n} ${u}`}
function recipe(id){return state.recipes[id]||null}
function pantryMap(data){const m={};for(const p of data.pantry||[]){const[v,u]=normalize(p.amount,p.unit);m[`${p.name}|${u}`]=(m[`${p.name}|${u}`]||0)+v}return m}
function todayNeeds(data){const d=dayKey(),need=new Map();for(const [slot] of MEALS){const r=recipe(data.plan?.[d]?.[slot]);if(!r)continue;for(const [name,a,u,cat] of r.ingredients||[]){const[v,nu]=normalize(a,u),k=`${name}|${nu}|${cat}`;need.set(k,(need.get(k)||0)+v)}}const pantry=pantryMap(data),missing=[],owned=[];for(const[k,a]of need){const[name,u,cat]=k.split('|'),have=pantry[`${name}|${u}`]||0,left=Math.max(0,a-have);if(left>0)missing.push({name,amount:left,unit:u,category:cat});else owned.push({name,amount:a,unit:u,category:cat})}return{missing,owned}}
function weekShopping(data){const need=new Map();for(const d of ['周一','周二','周三','周四','周五','周六','周日'])for(const[slot]of MEALS){const r=recipe(data.plan?.[d]?.[slot]);if(!r)continue;for(const[name,a,u,cat]of r.ingredients||[]){const[v,nu]=normalize(a,u),k=`${name}|${nu}|${cat}`;need.set(k,(need.get(k)||0)+v)}}const pantry=pantryMap(data),out=[];for(const[k,a]of need){const[name,u,cat]=k.split('|'),left=Math.max(0,a-(pantry[`${name}|${u}`]||0));if(left>0)out.push({id:`auto:${name}:${u}`,name,amount:left,unit:u,category:cat})}return[...out,...(data.manualShopping||[])];}
function completion(){try{return JSON.parse(localStorage.getItem('et-meal-completion-v11000')||'{}')||{}}catch{return{}}}
function setComplete(slot,value){const all=completion(),key=`${iso()}:${slot}`;if(value)all[key]=true;else delete all[key];localStorage.setItem('et-meal-completion-v11000',JSON.stringify(all));renderHome();renderToday();}
function mealStatus(slot,time){if(completion()[`${iso()}:${slot}`])return['已完成','done'];const[nowH,nowM]=[new Date().getHours(),new Date().getMinutes()], [h,m]=time.split(':').map(Number),delta=(nowH*60+nowM)-(h*60+m);if(Math.abs(delta)<=75)return['进行中','now'];return delta<0?['待开始','']:['待记录',''];}
async function waitRuntime(){for(let i=0;i<50;i++){if(window.Shiguang?.supabase)return window.Shiguang;await new Promise(r=>setTimeout(r,100))}return window.Shiguang||null}
async function loadRecipes(){const rt=await waitRuntime();state.user=rt?.user||null;state.profile=rt?.profile||null;if(!rt?.supabase||!state.user)return;const{data,error}=await rt.supabase.from('recipes').select('id,name,category,cook_time,difficulty,ingredients,image_path').order('created_at',{ascending:false});if(error)return;for(const r of data||[]){let image='assets/images/recipe-placeholder.svg';if(r.image_path){const s=await rt.supabase.storage.from('recipe-images').createSignedUrl(r.image_path,3600);if(s.data?.signedUrl)image=s.data.signedUrl}state.recipes[r.id]={id:r.id,name:r.name,category:r.category,time:r.cook_time,difficulty:r.difficulty,ingredients:r.ingredients||[],image};}}
async function loadRemote(force=false){if(!force&&Date.now()-state.remoteAt<15000)return;const rt=await waitRuntime();state.user=rt?.user||null;state.profile=rt?.profile||null;if(!rt?.supabase||!state.user){state.groups=[];state.members=[];state.dishes=[];state.remoteAt=Date.now();return}try{const g=await rt.supabase.from('food_groups').select('id,name,owner_id,created_at').order('created_at',{ascending:false});state.groups=g.data||[];if(state.groups.length){const ids=state.groups.map(x=>x.id);const m=await rt.supabase.from('group_members').select('group_id,user_id,member_name,member_role').in('group_id',ids);state.members=m.data||[];const active=localStorage.getItem('fansfood-active-group')||state.groups[0].id;const ds=await rt.supabase.from('site_dishes').select('id,name,category,image_path,image_url,group_id,is_active').eq('group_id',active).eq('is_active',true).limit(3);state.dishes=await Promise.all((ds.data||[]).map(async x=>{let image=x.image_url||'';if(!image&&x.image_path){const s=await rt.supabase.storage.from('dish-images').createSignedUrl(x.image_path,1800);image=s.data?.signedUrl||''}return{...x,image}}));}else{state.members=[];state.dishes=[]}}catch(e){console.warn('首页远端摘要读取失败',e)}state.remoteAt=Date.now();}
function profileName(){return state.profile?.display_name?.trim()||state.profile?.username||'食光朋友'}
function roleName(){return state.profile?.food_role==='chef'?'大厨':state.profile?.food_role==='foodie'?'美食家':'食光朋友'}
function initials(v){return(String(v||'食光').trim().slice(0,2)||'食光').toUpperCase()}
function mealMarkup(data,slot,time,icon){const r=recipe(data.plan?.[dayKey()]?.[slot]),[status,cls]=mealStatus(slot,time);return`<article class="et-meal">${r?`<img class="et-meal-image" src="${esc(r.image)}" alt="${esc(r.name)}">`:`<div class="et-meal-empty">${svg(icon)}</div>`}<div class="et-meal-body"><div class="et-meal-top"><b>${slot}</b><span class="et-meal-time">${time}</span></div><h3>${r?esc(r.name):'还没有安排'}</h3><span class="et-status ${cls}">${r?status:'待安排'}</span></div></article>`}
function missingMarkup(data){const{missing}=todayNeeds(data);return missing.length?`<div class="et-missing"><div class="et-missing-main"><span class="et-missing-icon">${svg('cart')}</span><div><b>还缺 ${missing.length} 样食材，需要采购</b><span>${missing.slice(0,3).map(x=>x.name).join('、')}${missing.length>3?' 等':''}，采购清单已经按库存自动计算。</span></div></div><button class="et-mini-cta" data-go="#shopping">去采购</button></div>`:`<div class="et-missing ok"><div class="et-missing-main"><span class="et-missing-icon">${svg('check')}</span><div><b>今天需要的食材已经准备齐啦</b><span>冰箱库存可以覆盖今天已安排菜谱的食材。</span></div></div><button class="et-mini-cta" data-go="#ingredients">查看食材</button></div>`}
function groupMarkup(){if(!state.user)return'<div class="et-empty"><b>登录后查看小饭桌</b><span>群组信息会和账号云端同步。</span></div>';if(!state.groups.length)return'<div class="et-empty"><b>还没有小饭桌</b><span>创建一个群组，和朋友一起决定吃什么。</span></div>';return`<div class="et-group-list">${state.groups.slice(0,3).map(g=>{const n=state.members.filter(m=>m.group_id===g.id).length;return`<a class="et-group-row" href="#groups"><span class="et-group-icon">${svg('users')}</span><div><b>${esc(g.name)}</b><small>${n} 人 · 小饭桌</small></div><em>进行中</em></a>`}).join('')}</div>`}
function tomorrowMarkup(){if(!state.dishes.length)return'<div class="et-empty"><b>明天还没有候选菜</b><span>进入小饭桌发起第一个提议。</span></div>';return`<div class="et-tomorrow-candidates">${state.dishes.map(d=>`<div class="et-candidate">${d.image?`<img src="${esc(d.image)}" alt="${esc(d.name)}">`:`<div class="et-day-empty">暂无图片</div>`}<b>${esc(d.name)}</b><small>${esc(d.category||'候选菜')}</small></div>`).join('')}</div>`}
function weekMarkup(data){return`<div class="et-week-strip">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);const key=dayKey(d),slots=data.plan?.[key]||{},rid=slots['晚餐']||slots['午餐']||slots['早餐'],r=recipe(rid);return`<div class="et-day-card ${i===0?'today':''}" data-date-day="${key}">${r?`<img src="${esc(r.image)}" alt="${esc(r.name)}">`:'<div class="et-day-empty">未安排</div>'}<b>${i===0?'今天':i===1?'明天':key}</b><span>${r?esc(r.name):'今天还没有安排'}</span></div>`}).join('')}</div>`}
function purchaseMarkup(data){const items=todayNeeds(data).missing;return items.length?`<div class="et-count-big">${items.length}</div><p>种食材需要为今天准备</p><div class="et-purchase-list">${items.slice(0,4).map(x=>`<div class="et-purchase-row"><span>${esc(x.name)}</span><b>${fmt(x.amount,x.unit)}</b></div>`).join('')}</div>`:`<div class="et-count-big" style="color:var(--et-green)">0</div><p>今天不需要额外采购啦</p><div class="et-owned-list"><span>库存已覆盖今日计划</span></div>`}
function fridgeMarkup(data){const counts={蔬菜:0,肉类:0,蛋奶:0,调料:0};for(const p of data.pantry||[]){if(p.category==='蔬菜'||p.category==='水果')counts.蔬菜++;else if(p.category==='肉蛋')counts.肉类++;else if(p.category==='乳制品')counts.蛋奶++;else if(p.category==='调味料')counts.调料++}return`<div class="et-fridge-grid">${Object.entries(counts).map(([k,v])=>`<div class="et-fridge-stat"><b>${v}</b><span>${k}</span></div>`).join('')}</div><div class="et-fridge-total">食材总数 <b>${(data.pantry||[]).length}</b> 种</div>`}
function skeletonHome(){return`<div class="et-home"><div class="et-welcome"><div><div class="et-skeleton" style="width:260px;height:34px"></div><div class="et-skeleton" style="width:150px;height:12px;margin-top:9px"></div></div></div><div class="et-home-primary"><div class="et-skeleton" style="height:390px;border-radius:24px"></div><div class="et-skeleton" style="height:280px;border-radius:20px"></div></div></div>`}
function renderHome(){const root=$('#etHomeDashboard');if(!root)return;const data=localState(),name=profileName();root.innerHTML=`<div class="et-home"><section class="et-welcome"><div><h1>嗨，欢迎回来，${esc(name)} 👋</h1><p>好好吃饭，好好生活</p></div><span class="et-date-pill">${prettyDate()}</span></section><div class="et-home-primary"><section class="card et-today-card"><div class="et-card-head"><div><span class="eyebrow">TODAY PLAN</span><h2>今日计划</h2><p>${prettyDate()} · 先看今天，再想明天</p></div><button class="et-text-link" data-go="#today">查看完整计划 →</button></div><div class="et-meal-grid">${MEALS.map(m=>mealMarkup(data,...m)).join('')}</div>${missingMarkup(data)}</section><aside class="card et-group-summary"><div class="et-section-head"><div><span class="eyebrow">MY GROUPS</span><h2>我的群组</h2><p>最近的小饭桌</p></div><button class="et-text-link" data-go="#groups">查看全部 →</button></div>${groupMarkup()}</aside></div><div class="et-home-second"><section class="card et-module"><div class="et-section-head"><div><span class="eyebrow">TOMORROW</span><h2>明天吃什么</h2><p>${(()=>{const d=new Date();d.setDate(d.getDate()+1);return prettyDate(d)})()}</p></div><button class="et-text-link" data-go="#tomorrow">去投票 →</button></div>${tomorrowMarkup()}</section><section class="card et-module"><div class="et-section-head"><div><span class="eyebrow">NEXT 7 DAYS</span><h2>近七天菜谱</h2><p>每天只看一个代表菜，完整安排进入“我的七天”</p></div><button class="et-text-link" data-go="#menu">查看完整安排 →</button></div>${weekMarkup(data)}</section></div><div class="et-home-third"><section class="card et-module"><div class="et-section-head"><div><span class="eyebrow">PURCHASE</span><h2>采购提醒</h2><p>只看今天计划真正缺的食材</p></div><button class="et-text-link" data-go="#shopping">查看清单 →</button></div>${purchaseMarkup(data)}</section><section class="card et-module"><div class="et-section-head"><div><span class="eyebrow">FRIDGE</span><h2>我的冰箱</h2><p>首页只展示库存摘要</p></div><button class="et-text-link" data-go="#pantry">查看全部 →</button></div>${fridgeMarkup(data)}</section></div></div>`;bindActions(root)}
function todayMealCard(data,slot,time,icon){const r=recipe(data.plan?.[dayKey()]?.[slot]),[label,cls]=mealStatus(slot,time),done=cls==='done';if(!r)return`<article class="card et-today-meal-card"><div class="et-today-photo-empty">${svg(icon)}</div><div class="et-today-meal-copy"><div class="et-today-meal-head"><h3>${slot} · ${time}</h3><span class="et-status">待安排</span></div><p>今天这一餐还没有安排。</p><div class="et-meal-actions"><button class="et-small-button" data-go="#menu">添加今日计划</button></div></div></article>`;return`<article class="card et-today-meal-card"><img src="${esc(r.image)}" alt="${esc(r.name)}"><div class="et-today-meal-copy"><div class="et-today-meal-head"><h3>${slot} · ${time}</h3><span class="et-status ${cls}">${label}</span></div><p>${esc(r.name)} · ${r.time||'—'} 分钟 · ${esc(r.difficulty||'')}</p><div class="et-ingredient-tags">${(r.ingredients||[]).map(x=>`<span>${esc(x[0])}</span>`).join('')}</div><div class="et-meal-actions"><button class="et-small-button" data-open-recipe="${esc(r.id)}">查看菜谱</button><button class="et-small-button ${done?'complete':''}" data-complete="${slot}">${done?'✓ 已完成':'标记已完成'}</button></div></div></article>`}
function renderToday(){const root=$('#etTodayContent');if(!root)return;const data=localState(),{missing,owned}=todayNeeds(data);root.innerHTML=`<div class="et-today-page"><div class="page-title"><div><span class="eyebrow">TODAY</span><h1>今日计划</h1><p>${prettyDate()} · 今天吃什么、缺什么、要不要采购，一页看清。</p></div></div><div class="et-today-layout"><div class="et-today-main">${MEALS.map(m=>todayMealCard(data,...m)).join('')}</div><aside class="et-today-side"><section class="card et-side-module"><h3>今日采购</h3><p>${missing.length?`还缺 ${missing.length} 样食材。采购页会继续按你的日期清单管理。`:'今天计划需要的食材已经准备齐。'}</p><div class="et-purchase-list">${missing.slice(0,5).map(x=>`<div class="et-purchase-row"><span>${esc(x.name)}</span><b>${fmt(x.amount,x.unit)}</b></div>`).join('')}</div><div class="et-meal-actions"><button class="et-small-button" data-go="#shopping">打开采购清单</button></div></section><section class="card et-side-module"><h3>已经拥有</h3><p>按菜谱食材与冰箱库存自动匹配。</p><div class="et-owned-list">${owned.length?owned.map(x=>`<span>✓ ${esc(x.name)}</span>`).join(''):'<span>暂无匹配库存</span>'}</div><div class="et-meal-actions"><button class="et-small-button" data-go="#pantry">查看冰箱</button></div></section><section class="card et-side-module"><h3>明天吃什么</h3><p>${state.dishes.length?`当前小饭桌有 ${state.dishes.length} 道候选菜。`:'还没有候选菜，去和大家一起提议。'}</p><div class="et-meal-actions"><button class="et-small-button" data-go="#tomorrow">查看明日计划</button></div></section></aside></div></div>`;bindActions(root)}
function renderIngredients(){const root=$('#etIngredientsContent');if(!root)return;const data=localState(),groups={};for(const p of data.pantry||[])(groups[p.category||'其他']??=[]).push(p);root.innerHTML=`<div class="et-simple-page"><div class="page-title"><div><span class="eyebrow">INGREDIENT LIBRARY</span><h1>食材库</h1><p>按类别快速了解目前已经拥有的食材；详细数量和保质期仍在“我的冰箱”管理。</p></div></div>${Object.keys(groups).length?`<div class="et-category-list">${Object.entries(groups).map(([k,v])=>`<section class="card et-category-card"><b>${v.length}</b><span>${esc(k)}</span><div class="et-owned-list">${v.slice(0,5).map(x=>`<span>${esc(x.name)}</span>`).join('')}</div></section>`).join('')}</div>`:'<div class="et-empty"><b>食材库还是空的</b><span>先去“我的冰箱”添加库存。</span></div>'}</div>`;bindActions(root)}
function renderStats(){const root=$('#etStatsContent');if(!root)return;const data=localState(),planned=Object.values(data.plan||{}).reduce((n,d)=>n+Object.values(d||{}).filter(Boolean).length,0),shopping=weekShopping(data),done=Object.values(completion()).filter(Boolean).length;root.innerHTML=`<div class="et-simple-page"><div class="page-title"><div><span class="eyebrow">RECORDS</span><h1>统计与记录</h1><p>只使用你的真实菜单、库存和完成记录，不生成模拟数字。</p></div></div><div class="et-simple-grid"><section class="card et-simple-stat"><b>${planned}</b><span>当前七天已安排餐次</span></section><section class="card et-simple-stat"><b>${(data.pantry||[]).length}</b><span>冰箱食材种类</span></section><section class="card et-simple-stat"><b>${shopping.length}</b><span>当前采购项目</span></section><section class="card et-simple-stat"><b>${(data.favorites||[]).length}</b><span>收藏食谱</span></section><section class="card et-simple-stat"><b>${done}</b><span>本设备累计标记完成餐次</span></section></div></div>`}
function renderSettings(){const root=$('#etSettingsContent');if(!root)return;root.innerHTML=`<div class="et-simple-page"><div class="page-title"><div><span class="eyebrow">SETTINGS</span><h1>设置</h1><p>账号、昵称和身份继续使用现有账户系统管理。</p></div></div><section class="card et-side-module"><h3>${esc(profileName())}</h3><p>${esc(roleName())}${state.profile?.username?` · @${esc(state.profile.username)}`:''}</p><div class="et-meal-actions"><button class="btn primary" id="etOpenAccount">打开账户设置</button></div></section></div>`;$('#etOpenAccount')?.addEventListener('click',()=>$('#accountBtn')?.click())}
function ensurePages(){const main=$('main');if(!main)return;const add=(id,inner)=>{if($('#'+id))return;const s=document.createElement('section');s.id=id;s.className='page';s.innerHTML=inner;main.appendChild(s)};add('today','<div id="etTodayContent"></div>');add('ingredients','<div id="etIngredientsContent"></div>');add('stats','<div id="etStatsContent"></div>');add('settings','<div id="etSettingsContent"></div>')}
function buildShell(){document.body.classList.remove('warm-dining');document.body.classList.add('et-v11000','warm-dining');$('.wd-sidebar')?.remove();$('.wd-mobile-bottom')?.remove();const old=$('.et-sidebar');if(old)old.remove();const nav=[['home','首页','home'],['today','今日计划','calendar'],['groups','我的群组','users'],['buddies','饭搭子','utensils'],['recipes','菜谱','book'],['shopping','采购','cart'],['ingredients','食材库','package'],['pantry','我的冰箱','fridge'],['tomorrow','明天吃什么','clock'],['stats','统计与记录','chart'],['settings','设置','settings']];const aside=document.createElement('aside');aside.className='et-sidebar';aside.innerHTML=`<a class="et-brand" href="#home"><img src="assets/images/eating-time-mark.svg" alt="食光"><div><strong>食光</strong><span>EATING TIME · v${VERSION}</span></div></a><nav class="et-nav">${nav.map(([id,label,ic])=>`<a href="#${id}" data-et-route="${id}">${svg(ic)}<span>${label}</span></a>`).join('')}</nav><div class="et-sidebar-spacer"></div><div class="et-side-user"><span class="et-avatar" id="etSideAvatar">${initials(profileName())}</span><div><b id="etSideName">${esc(profileName())}</b><small id="etSideRole">${esc(roleName())}</small></div><button class="et-side-settings" id="etSideSettings" aria-label="账户设置">${svg('settings')}</button></div>`;document.body.appendChild(aside);const top=$('body>.topbar');if(top){const actions=$('.top-actions',top);if(actions&&!$('.et-top-search',top)){actions.insertAdjacentHTML('afterbegin',`<label class="et-top-search">${svg('search')}<input id="etGlobalSearch" placeholder="搜索菜谱、食材、群组……"></label><button class="et-top-icon" id="etNotice" aria-label="通知">${svg('bell')}</button><div class="et-top-profile"><div class="et-top-profile-copy"><b id="etTopName">${esc(profileName())}</b><small id="etTopRole">${esc(roleName())}</small></div></div>`);$('#etGlobalSearch')?.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=e.currentTarget.value.trim();location.hash='#recipes';setTimeout(()=>{const input=$('#recipeSearch');if(input){input.value=q;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}},120)});$('#etNotice')?.addEventListener('click',()=>toastUI('通知中心将在有真实消息时显示提醒'));}}buildMobile();$('#etSideSettings')?.addEventListener('click',()=>$('#accountBtn')?.click());updateChrome();updateNav()}
function buildMobile(){if($('.et-mobile-bottom'))return;const nav=document.createElement('nav');nav.className='et-mobile-bottom';nav.innerHTML=`<a href="#home" data-mobile-route="home">${svg('home')}<span>首页</span></a><a href="#recipes" data-mobile-route="recipes">${svg('book')}<span>菜谱</span></a><button class="et-mobile-plus" id="etMobilePlus" aria-label="快捷添加">${svg('plus')}</button><a href="#shopping" data-mobile-route="shopping">${svg('cart')}<span>采购</span></a><a href="#settings" data-mobile-route="settings">${svg('user')}<span>我的</span></a>`;document.body.appendChild(nav);const back=document.createElement('div');back.className='et-sheet-backdrop';back.id='etSheetBackdrop';document.body.appendChild(back);const sheet=document.createElement('section');sheet.className='et-sheet';sheet.id='etActionSheet';sheet.innerHTML=`<div class="et-sheet-handle"></div><h3>快速添加</h3><div class="et-sheet-actions">${[['menu','添加今日计划','安排今天或未来七天吃什么','calendar'],['recipes','发布菜谱','把自己的菜谱保存到食光','book'],['tomorrow','发起投票','和小饭桌一起决定明天吃什么','clock'],['shopping','添加采购','补充一项要买的东西','cart'],['pantry','添加冰箱食材','把买回来的食材加入库存','fridge'],['groups','创建群组','建立一个新的小饭桌','users']].map(([id,b,s,ic])=>`<button class="et-sheet-action" data-sheet-go="#${id}">${svg(ic)}<div><b>${b}</b><span>${s}</span></div></button>`).join('')}</div>`;document.body.appendChild(sheet);const toggle=v=>{sheet.classList.toggle('open',v);back.classList.toggle('open',v)};$('#etMobilePlus').onclick=()=>toggle(true);back.onclick=()=>toggle(false);$$('[data-sheet-go]',sheet).forEach(b=>b.onclick=()=>{toggle(false);const h=b.dataset.sheetGo;location.hash=h;setTimeout(()=>{if(h==='#recipes')$('#newRecipeBtn')?.click();if(h==='#shopping')$('#quickAddName')?.focus();if(h==='#pantry')$('#pantryName')?.focus()},180)})}
function wrapHome(){const home=$('#home');if(!home||$('#etHomeDashboard'))return;const legacy=document.createElement('div');legacy.className='et-legacy-home';while(home.firstChild)legacy.appendChild(home.firstChild);const root=document.createElement('div');root.id='etHomeDashboard';root.innerHTML=skeletonHome();home.append(root,legacy)}
function bindActions(root=document){$$('[data-go]',root).forEach(el=>el.onclick=()=>{location.hash=el.dataset.go});$$('[data-date-day]',root).forEach(el=>el.onclick=()=>{location.hash='#menu';setTimeout(()=>{const btn=[...$$('#weekTabs button')].find(x=>x.dataset.day===el.dataset.dateDay);btn?.click()},180)});$$('[data-complete]',root).forEach(b=>b.onclick=()=>{const key=`${iso()}:${b.dataset.complete}`,done=!!completion()[key];setComplete(b.dataset.complete,!done)});$$('[data-open-recipe]',root).forEach(b=>b.onclick=()=>{location.hash='#recipes';setTimeout(()=>document.querySelector(`[data-open="${CSS.escape(b.dataset.openRecipe)}"]`)?.click(),180)})}
function updateNav(){const id=(location.hash||'#home').slice(1);$$('[data-et-route]').forEach(a=>a.classList.toggle('active',a.dataset.etRoute===id));$$('[data-mobile-route]').forEach(a=>a.classList.toggle('active',a.dataset.mobileRoute===id))}
function updateChrome(){const n=profileName(),r=roleName();$('#etSideName')&&($('#etSideName').textContent=n);$('#etSideRole')&&($('#etSideRole').textContent=state.profile?.username?`${r} · @${state.profile.username}`:r);$('#etSideAvatar')&&($('#etSideAvatar').textContent=initials(n));$('#etTopName')&&($('#etTopName').textContent=n);$('#etTopRole')&&($('#etTopRole').textContent=r);const badge=$('.brand small');if(badge)badge.textContent=`v${VERSION}`}
function toastUI(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(el._et);el._et=setTimeout(()=>el.classList.remove('show'),1900)}
function routeRefresh(){updateNav();if(location.hash==='#home'||!location.hash){renderHome();loadRemote().then(renderHome)}if(location.hash==='#today'){renderToday();loadRemote().then(renderToday)}if(location.hash==='#ingredients')renderIngredients();if(location.hash==='#stats')renderStats();if(location.hash==='#settings')renderSettings();window.SHIGUANG_SHOW_ROUTE?.()}
async function refreshProfile(){const rt=await waitRuntime();state.user=rt?.user||null;state.profile=rt?.profile||null;updateChrome();await loadRecipes();await loadRemote(true);renderHome();renderToday();renderSettings()}
function monitorLocal(){setInterval(()=>{const raw=localStorage.getItem('shiguang-v2-state')||'';if(raw===state.lastLocal)return;state.lastLocal=raw;if(location.hash==='#home'||!location.hash)renderHome();if(location.hash==='#today')renderToday();if(location.hash==='#ingredients')renderIngredients();if(location.hash==='#stats')renderStats()},900)}
async function init(){ensurePages();wrapHome();buildShell();state.lastLocal=localStorage.getItem('shiguang-v2-state')||'';renderHome();renderToday();renderIngredients();renderStats();renderSettings();bindActions(document);window.SHIGUANG_SHOW_ROUTE?.();routeRefresh();monitorLocal();refreshProfile();window.addEventListener('hashchange',routeRefresh);window.addEventListener('shiguang-profile-ready',e=>{state.user=e.detail?.user||state.user;state.profile=e.detail?.profile||state.profile;updateChrome();loadRecipes().then(()=>{renderHome();renderToday()});loadRemote(true).then(()=>{renderHome();renderToday()})});window.addEventListener('fansfood-group-changed',()=>loadRemote(true).then(()=>{renderHome();renderToday()}));window.addEventListener('fansfood-account-changed',refreshProfile)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
