import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0/+esm'

const SUPABASE_URL='https://ozegqygkyoigvnfkbuyd.supabase.co'
const SUPABASE_KEY='sb_publishable_YTjdt2VvvyWIeRsTRgpe2g_Q2cO4Mwd'
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'classflow-auth-v1'}})
const $=id=>document.getElementById(id)
const flagDefs=[{key:'重点',label:'重点 / Key',icon:'★'},{key:'考试',label:'考试 / Exam',icon:'✓'},{key:'没听懂',label:'没听懂 / Unsure',icon:'?'},{key:'例子',label:'例子 / Example',icon:'◇'}]
const state={user:null,sessionId:null,entries:[],notes:'',isListening:false,interim:'',pipeline:'idle',micStream:null,recognition:null,peer:null,dataChannel:null,rtInterim:new Map(),speechStops:new Map(),lastSpeechStop:0,pendingSegment:null,pendingTimer:null,latencies:[],saving:0,recorder:null,recordingStartedAt:0,recordingTimer:null,chunkIndex:0,chunkStartAt:0,uploadedChunks:0,pendingChunks:0,recordings:[],titleTimer:null}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function clock(){return new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())}
function fmtMs(ms){if(!Number.isFinite(ms))return'—';return ms<1000?`${Math.round(ms)} ms`:`${(ms/1000).toFixed(ms<10000?2:1)} s`}
function fmtDuration(ms){const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60),r=s%60;return`${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function empty(text){return`<div class="empty">${esc(text)}</div>`}
function setStatus(text){$('status').textContent=text}
function setSync(busy=false){state.saving=Math.max(0,state.saving+(busy?1:-1));$('syncPill').textContent=state.saving?'☁ 同步中… / Syncing':'☁ 已同步 / Synced'}
function dataFlag(f){return`data-flag="${esc(f)}"`}
function renderFlags(flags){return flags.map(f=>`<b ${dataFlag(f)}>${esc(f)}</b>`).join('')}
function updateMetrics(){const arr=state.latencies.slice(-20),last=arr.at(-1),avg=arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:NaN;$('lastLatency').textContent=fmtMs(last);$('avgLatency').textContent=fmtMs(avg);$('latencyPill').textContent=`延迟 / Latency: ${fmtMs(last)}`;$('pendingChunks').textContent=String(state.pendingChunks);$('recordingChunks').textContent=`${state.uploadedChunks} 段已上传`}
function render(){$('recordCount').textContent=`${state.entries.length} 条记录 / records`;$('recordButton').classList.toggle('stop',state.isListening);$('recordLabel').textContent=state.isListening?'暂停内测 / Pause':'开始内测 / Start Beta';$('recordButton').querySelector('span').textContent=state.isListening?'■':'●';$('pipelinePill').textContent=`管线 / Pipeline: ${state.pipeline==='realtime'?'Realtime':state.pipeline==='browser'?'Browser':state.pipeline==='connecting'?'Connecting…':'—'}`;$('realtimeDot').classList.toggle('live',state.pipeline==='realtime');$('realtimeStatus').textContent=state.pipeline==='realtime'?'已连接 / Connected':state.pipeline==='connecting'?'连接中 / Connecting':state.pipeline==='browser'?'已降级 / Fallback':'未连接 / Idle';const orig=state.entries.map(e=>`<article class="speech-card"><div class="meta"><span>${esc(e.time)}</span>${renderFlags(e.flags)}</div><p>${esc(e.original)}</p></article>`).join('');$('originalStream').innerHTML=orig+(state.interim?`<article class="speech-card interim"><div class="meta"><span>${state.pipeline==='realtime'?'Realtime delta':'Listening'}</span></div><p>${esc(state.interim)}</p></article>`:'')||empty('点击“开始内测 / Start Beta”，这里会显示流式原文。');const trans=state.entries.map(e=>`<article class="speech-card translated"><div class="meta"><span>${esc(e.time)}</span>${e.latencyMs?`<span>⚡ ${fmtMs(e.latencyMs)}</span>`:''}</div><p class="${e.translation?.startsWith('⚠')?'error':''}">${esc(e.translation||'翻译中… / Translating')}</p><div class="flag-row">${flagDefs.map(f=>`<button data-entry="${esc(e.id)}" data-flag="${esc(f.key)}" class="${e.flags.includes(f.key)?'selected':''}">${f.icon} ${esc(f.label)}</button>`).join('')}</div></article>`).join('');$('translationStream').innerHTML=trans||empty('最终转写一到达就立即并行翻译，不等待云端保存。');const review=state.entries.map(e=>`<article class="review-entry"><div class="review-meta"><span>${esc(e.time)}</span>${renderFlags(e.flags)}</div><p class="${e.translation?.startsWith('⚠')?'error':''}">${esc(e.translation||'翻译中… / Translating')}</p></article>`).join('');$('reviewArea').innerHTML=review||empty('这里仅显示连续译文，AI 课堂笔记独立显示在页面下方。');$('notesOutput').hidden=!state.notes;if(state.notes)$('notesOutput').textContent=state.notes;$('generateNotes').disabled=!state.entries.length;$('exportMd').disabled=!state.entries.length;document.querySelectorAll('.flag-row button').forEach(b=>b.onclick=()=>toggleFlag(b.dataset.entry,b.dataset.flag));updateMetrics();requestAnimationFrame(()=>['originalStream','translationStream','reviewArea'].forEach(id=>{const el=$(id);if(el)el.scrollTop=el.scrollHeight}))}
async function ensureCloudSession(){if(state.sessionId)return state.sessionId;setSync(true);const {data,error}=await supabase.from('classflow_sessions').insert({title:$('classTitle').value||'ClassFlow Beta',source_language:$('sourceLanguage').value,target_language:'zh-CN'}).select('id').single();setSync(false);if(error)throw error;state.sessionId=data.id;state.chunkIndex=0;await Promise.all([loadRecordings(),retryPendingUploads()]);return data.id}
async function saveSessionMeta(){if(!state.sessionId)return;setSync(true);const {error}=await supabase.from('classflow_sessions').update({title:$('classTitle').value||'ClassFlow Beta',source_language:$('sourceLanguage').value,updated_at:new Date().toISOString()}).eq('id',state.sessionId);setSync(false);if(error)setStatus(`课堂信息同步失败 / Metadata sync failed: ${error.message}`)}
async function saveSegment(entry){try{const sessionId=await ensureCloudSession(),initialTranslation=entry.translation?.startsWith('翻译中')?'':entry.translation;setSync(true);const {data,error}=await supabase.from('classflow_segments').insert({session_id:sessionId,seq:entry.seq,source_text:entry.original,translation:initialTranslation||'',flags:entry.flags}).select('id').single();setSync(false);if(error)throw error;entry.cloudId=data.id;if(entry.translation&&!entry.translation.startsWith('翻译中')&&entry.translation!==initialTranslation)await updateSegment(entry,{translation:entry.translation})}catch(err){setSync(false);setStatus(`字幕已保留在页面，本次云同步失败 / Local transcript kept; cloud sync failed: ${err.message||err}`)}}
async function updateSegment(entry,patch){if(!entry.cloudId)return;setSync(true);const {error}=await supabase.from('classflow_segments').update(patch).eq('id',entry.cloudId);setSync(false);if(error)setStatus(`云同步失败 / Cloud sync failed: ${error.message}`)}
async function callAI(body){const {data,error}=await supabase.functions.invoke('classflow-ai',{body});if(error){let msg=error.message||'AI request failed';try{const c=await error.context?.json?.();if(c?.error)msg=c.error}catch{};throw new Error(msg)}return data}
async function translateEntry(entry){if($('sourceLanguage').value==='zh-CN'){entry.translation=entry.original;entry.translationDoneAt=performance.now();entry.latencyMs=entry.translationDoneAt-entry.baseAt;state.latencies.push(entry.latencyMs);render();if(entry.cloudId)await updateSegment(entry,{translation:entry.translation});return}try{const d=await callAI({action:'translate',text:entry.original,sourceLanguage:$('sourceLanguage').value,courseTitle:$('classTitle').value});entry.translation=d.translation||''}catch(err){entry.translation=`⚠ ${err.message||'翻译失败 / Translation failed'}`}entry.translationDoneAt=performance.now();entry.latencyMs=Math.max(0,entry.translationDoneAt-entry.baseAt);state.latencies.push(entry.latencyMs);render();if(entry.cloudId)await updateSegment(entry,{translation:entry.translation})}
async function commitTranscript(text,meta={}){const clean=String(text||'').replace(/\s+/g,' ').trim();if(!clean)return;const entry={id:crypto.randomUUID(),cloudId:null,seq:state.entries.length+1,time:clock(),original:clean,translation:'翻译中… / Translating',flags:[],baseAt:meta.speechStopAt||meta.completedAt||performance.now(),source:meta.source||state.pipeline};state.entries.push(entry);state.interim='';render();await Promise.allSettled([saveSegment(entry),translateEntry(entry)])}
function terminal(text){return/[.!?。！？;；:]$/.test(text.trim())}
function queueTranscript(text,meta={}){const clean=String(text||'').replace(/\s+/g,' ').trim();if(!clean)return;const mode=$('vadMode').value,isRealtime=meta.source==='realtime',words=clean.split(/\s+/).length,shouldWait=!terminal(clean)&&((!isRealtime)||mode==='server')&&(words<18||clean.length<100);if(!shouldWait){flushPendingSegment();commitTranscript(clean,meta);return}if(state.pendingSegment){state.pendingSegment.text=`${state.pendingSegment.text} ${clean}`.replace(/\s+/g,' ').trim();state.pendingSegment.meta.completedAt=meta.completedAt||state.pendingSegment.meta.completedAt;if(meta.speechStopAt)state.pendingSegment.meta.speechStopAt=meta.speechStopAt}else state.pendingSegment={text:clean,meta:{...meta}};clearTimeout(state.pendingTimer);state.pendingTimer=setTimeout(flushPendingSegment,isRealtime?330:650);state.interim=state.pendingSegment.text;render()}
function flushPendingSegment(){clearTimeout(state.pendingTimer);state.pendingTimer=null;const p=state.pendingSegment;state.pendingSegment=null;if(p){state.interim='';commitTranscript(p.text,p.meta)}}
async function getRealtimeToken(){const {data,error}=await supabase.functions.invoke('classflow-realtime-token',{body:{sourceLanguage:$('sourceLanguage').value,courseTitle:$('classTitle').value,vadMode:$('vadMode').value,eagerness:'auto',delay:'low'}});if(error)throw error;const token=data?.value||data?.client_secret?.value||data?.client_secret||data?.secret?.value;if(!token)throw new Error(data?.error||'Realtime ephemeral token missing');return token}
async function connectRealtime(stream){state.pipeline='connecting';render();$('segmentStatus').textContent=$('vadMode').value==='semantic'?'Semantic VAD + app merge':'Server VAD + app merge';const token=await getRealtimeToken(),pc=new RTCPeerConnection();state.peer=pc;const track=stream.getAudioTracks()[0];if(!track)throw new Error('No microphone audio track');pc.addTrack(track,stream);const dc=pc.createDataChannel('oai-events');state.dataChannel=dc;dc.addEventListener('open',()=>{state.pipeline='realtime';setStatus('Realtime 原生语音管线已连接 / Native Realtime pipeline connected');render()});dc.addEventListener('message',({data})=>{let ev;try{ev=JSON.parse(data)}catch{return}if(ev.type==='conversation.item.input_audio_transcription.delta'){const id=ev.item_id||'current',prev=state.rtInterim.get(id)||'';state.rtInterim.set(id,prev+(ev.delta||''));state.interim=Array.from(state.rtInterim.values()).join(' ').trim();render()}else if(ev.type==='conversation.item.input_audio_transcription.completed'){const id=ev.item_id||'current';state.rtInterim.delete(id);state.interim=Array.from(state.rtInterim.values()).join(' ').trim();const stopAt=state.speechStops.get(id)||state.lastSpeechStop||performance.now();state.speechStops.delete(id);queueTranscript(ev.transcript,{source:'realtime',itemId:id,completedAt:performance.now(),speechStopAt:stopAt})}else if(ev.type==='input_audio_buffer.speech_stopped'){const t=performance.now();state.lastSpeechStop=t;if(ev.item_id)state.speechStops.set(ev.item_id,t)}else if(ev.type==='error')setStatus(`Realtime 错误 / Realtime error: ${ev.error?.message||'unknown error'}`)});pc.addEventListener('connectionstatechange',()=>{if(['failed','disconnected'].includes(pc.connectionState)&&state.isListening&&$('pipelineMode').value==='auto'){setStatus('Realtime 连接中断，正在切换浏览器兼容识别 / Realtime lost; switching to browser fallback');cleanupRealtime();startBrowserRecognition()}});const offer=await pc.createOffer();await pc.setLocalDescription(offer);const response=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',body:offer.sdp,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/sdp'}});if(!response.ok)throw new Error(`Realtime SDP failed (${response.status}): ${await response.text()}`);await pc.setRemoteDescription({type:'answer',sdp:await response.text()})}
function cleanupRealtime(){try{state.dataChannel?.close()}catch{};try{state.peer?.close()}catch{};state.dataChannel=null;state.peer=null;state.rtInterim.clear()}
function startBrowserRecognition(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)throw new Error('This browser does not support Web Speech fallback');const r=new Recognition();r.lang=$('sourceLanguage').value;r.continuous=true;r.interimResults=true;state.recognition=r;state.pipeline='browser';render();r.onresult=ev=>{let interim='';for(let i=ev.resultIndex;i<ev.results.length;i++){const result=ev.results[i],text=result[0].transcript.trim();if(!text)continue;if(result.isFinal)queueTranscript(text,{source:'browser',completedAt:performance.now()});else interim+=text+' '}state.interim=interim.trim();render()};r.onerror=ev=>{if(ev.error!=='no-speech')setStatus(`浏览器识别异常 / Browser recognition: ${ev.error}`)};r.onend=()=>{if(state.isListening&&state.pipeline==='browser')setTimeout(()=>{try{r.start()}catch{}},250)};r.start();setStatus('已使用浏览器兼容识别 / Browser speech fallback active')}
function chooseMime(){const c=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'];return c.find(x=>window.MediaRecorder?.isTypeSupported?.(x))||''}
function extFor(mime){if(mime.includes('mp4'))return'm4a';if(mime.includes('ogg'))return'ogg';return'webm'}
function openAudioDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('classflow-beta-audio',1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('chunks'))db.createObjectStore('chunks',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbPut(record){const db=await openAudioDb();return new Promise((resolve,reject)=>{const tx=db.transaction('chunks','readwrite');tx.objectStore('chunks').put(record);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function dbDelete(id){const db=await openAudioDb();return new Promise((resolve,reject)=>{const tx=db.transaction('chunks','readwrite');tx.objectStore('chunks').delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function dbAll(){const db=await openAudioDb();return new Promise((resolve,reject)=>{const tx=db.transaction('chunks','readonly'),req=tx.objectStore('chunks').getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
async function refreshPendingCount(){try{const all=await dbAll();state.pendingChunks=all.filter(x=>x.userId===state.user?.id).length}catch{state.pendingChunks=0}updateMetrics()}
async function uploadChunk(rec){if(!state.user||!rec?.blob||!navigator.onLine)return false;const path=`${rec.userId}/${rec.sessionId}/${String(rec.index).padStart(5,'0')}.${extFor(rec.mimeType)}`;const {error:upErr}=await supabase.storage.from('classflow-recordings').upload(path,rec.blob,{contentType:rec.mimeType||'audio/webm',upsert:true});if(upErr)throw upErr;const {error:dbErr}=await supabase.from('classflow_recordings').insert({session_id:rec.sessionId,chunk_index:rec.index,storage_path:path,mime_type:rec.mimeType||'audio/webm',bytes:rec.blob.size,duration_ms:rec.durationMs,started_at:new Date(rec.createdAt).toISOString()});if(dbErr&&dbErr.code!=='23505')throw dbErr;await dbDelete(rec.id);state.uploadedChunks++;await refreshPendingCount();if(rec.sessionId===state.sessionId)await loadRecordings();return true}
async function persistRecordingChunk(blob){if(!blob?.size||!state.user||!state.sessionId)return;const now=Date.now(),duration=Math.max(1,now-state.chunkStartAt);state.chunkStartAt=now;const index=state.chunkIndex++,rec={id:`${state.user.id}:${state.sessionId}:${index}`,userId:state.user.id,sessionId:state.sessionId,index,blob,mimeType:blob.type||state.recorder?.mimeType||'audio/webm',durationMs:duration,createdAt:now-duration};await dbPut(rec);await refreshPendingCount();try{await uploadChunk(rec)}catch(err){setStatus(`录音片段已保存在本机，等待重试 / Audio kept locally: ${err.message||err}`)}}
async function retryPendingUploads(){if(!state.user||!navigator.onLine)return;const all=(await dbAll()).filter(x=>x.userId===state.user.id).sort((a,b)=>a.createdAt-b.createdAt);state.pendingChunks=all.length;updateMetrics();for(const rec of all){try{await uploadChunk(rec)}catch{break}}await refreshPendingCount()}
async function startRecorder(stream){if(!$('recordingToggle').checked||!window.MediaRecorder)return;const mime=chooseMime(),opts=mime?{mimeType:mime,audioBitsPerSecond:48000}:{audioBitsPerSecond:48000},recorder=new MediaRecorder(stream,opts);state.recorder=recorder;state.recordingStartedAt=Date.now();state.chunkStartAt=Date.now();$('recordingDot').classList.add('recording');$('recordingStatus').textContent='录音中 / Recording';recorder.ondataavailable=e=>{if(e.data?.size)persistRecordingChunk(e.data)};recorder.onstop=()=>{$('recordingDot').classList.remove('recording');$('recordingStatus').textContent='已暂停 / Paused'};recorder.start(30000);clearInterval(state.recordingTimer);state.recordingTimer=setInterval(()=>{$('recordingDuration').textContent=fmtDuration(Date.now()-state.recordingStartedAt)},1000)}
async function loadRecordings(){if(!state.sessionId){state.recordings=[];renderRecordingList();return}const {data,error}=await supabase.from('classflow_recordings').select('id,chunk_index,storage_path,mime_type,bytes,duration_ms,started_at').eq('session_id',state.sessionId).order('chunk_index');if(error)return;state.recordings=data||[];state.uploadedChunks=state.recordings.length;renderRecordingList();updateMetrics()}
function renderRecordingList(){$('recordingList').innerHTML=state.recordings.length?state.recordings.map(r=>`<button class="recording-item" data-recording="${r.id}"><b>▶ ${String(r.chunk_index+1).padStart(2,'0')}</b><span>${fmtDuration(r.duration_ms||30000)}</span><span>${Math.round((r.bytes||0)/1024)} KB</span></button>`).join(''):empty('还没有上传的录音片段 / No uploaded recording chunks yet');document.querySelectorAll('[data-recording]').forEach(b=>b.onclick=()=>playRecording(b.dataset.recording))}
async function playRecording(id){const r=state.recordings.find(x=>x.id===id);if(!r)return;const {data,error}=await supabase.storage.from('classflow-recordings').createSignedUrl(r.storage_path,600);if(error){setStatus(`录音读取失败 / Audio load failed: ${error.message}`);return}$('audioPlayer').src=data.signedUrl;$('audioPlayer').hidden=false;$('audioPlayer').play().catch(()=>{})}
async function startBeta(){if(state.isListening)return;try{await ensureCloudSession();state.micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});state.isListening=true;render();await startRecorder(state.micStream);const mode=$('pipelineMode').value;if(mode==='browser'){startBrowserRecognition();return}try{await connectRealtime(state.micStream)}catch(err){cleanupRealtime();if(mode==='auto'){setStatus(`Realtime 暂不可用，自动降级浏览器识别 / Auto fallback: ${err.message||err}`);startBrowserRecognition()}else{state.pipeline='idle';setStatus(`Realtime 启动失败 / Realtime failed: ${err.message||err}`);render()}}}catch(err){state.isListening=false;setStatus(`启动失败 / Start failed: ${err.message||err}`);render()}}
function stopBeta(){state.isListening=false;flushPendingSegment();try{state.recognition?.stop()}catch{};state.recognition=null;cleanupRealtime();state.pipeline='idle';try{if(state.recorder?.state!=='inactive')state.recorder.stop()}catch{};state.recorder=null;clearInterval(state.recordingTimer);state.recordingTimer=null;state.micStream?.getTracks().forEach(t=>t.stop());state.micStream=null;state.interim='';$('recordingDot').classList.remove('recording');$('recordingStatus').textContent='已暂停 / Paused';setStatus('已暂停；字幕、译文与录音片段继续后台同步 / Paused · syncing continues');render();retryPendingUploads()}
async function toggleFlag(id,flag){const e=state.entries.find(x=>x.id===id);if(!e)return;e.flags=e.flags.includes(flag)?e.flags.filter(x=>x!==flag):[...e.flags,flag];render();if(e.cloudId)await updateSegment(e,{flags:e.flags})}
function markLatest(flag){const e=state.entries.at(-1);if(e)toggleFlag(e.id,flag)}
async function generateNotes(){if(!state.entries.length)return;const b=$('generateNotes');b.disabled=true;b.textContent='正在整理… / Generating';setStatus('正在生成 AI 课堂笔记 / Generating notes');try{const d=await callAI({action:'notes',title:$('classTitle').value,entries:state.entries});state.notes=d.notes||'';$('notesOutput').hidden=!state.notes;$('notesOutput').textContent=state.notes;await ensureCloudSession();await supabase.from('classflow_sessions').update({notes:state.notes,updated_at:new Date().toISOString()}).eq('id',state.sessionId);setStatus('课堂笔记已生成并保存 / Notes generated and saved')}catch(err){setStatus(`笔记生成失败 / Notes failed: ${err.message||err}`)}finally{b.disabled=false;b.textContent='生成课堂笔记 / Generate Class Notes'}}
function exportMd(){const rows=state.entries.map(e=>`### ${e.time}${e.flags.length?` · ${e.flags.join(' / ')}`:''}\n\n**原文 / Original**：${e.original}\n\n**翻译 / Translation**：${e.translation}\n`).join('\n'),text=`# ${$('classTitle').value}\n\n${rows}${state.notes?`\n# AI 课堂笔记\n\n${state.notes}`:''}`,blob=new Blob([text],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${$('classTitle').value||'ClassFlow'}_beta.md`;a.click();URL.revokeObjectURL(url)}
async function newSession(){stopBeta();state.sessionId=null;state.entries=[];state.notes='';state.latencies=[];state.recordings=[];state.uploadedChunks=0;state.chunkIndex=0;$('classTitle').value='新课堂 / New Class';$('recordingDuration').textContent='00:00';renderRecordingList();render();setStatus('新课堂已准备 / New beta class ready')}
async function enterApp(session){state.user=session?.user||null;if(!state.user){$('authGate').hidden=false;$('appShell').hidden=true;return}$('authGate').hidden=true;$('appShell').hidden=false;$('accountEmail').textContent=state.user.email||'已登录';setStatus('ClassFlow 2.0 内测已准备 / Beta ready');await refreshPendingCount();retryPendingUploads();render()}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='正在登录… / Signing in';const {error}=await supabase.auth.signInWithPassword({email:$('authEmail').value.trim(),password:$('authPassword').value});$('authMessage').textContent=error?(error.message||'登录失败'):'登录成功 / Signed in'}
$('recordButton').onclick=()=>state.isListening?stopBeta():startBeta();$('quickFlags').querySelectorAll('button').forEach(b=>b.onclick=()=>markLatest(b.dataset.flag));$('generateNotes').onclick=generateNotes;$('exportMd').onclick=exportMd;$('newSession').onclick=newSession;$('retryUploads').onclick=retryPendingUploads;$('sourceLanguage').onchange=()=>{if(state.isListening){stopBeta();setStatus('语言已修改，请重新开始内测 / Language changed; start again')}saveSessionMeta()};$('pipelineMode').onchange=()=>{if(state.isListening){stopBeta();setStatus('语音管线已修改，请重新开始 / Pipeline changed; start again')}};$('vadMode').onchange=()=>{if(state.isListening){stopBeta();setStatus('断句模式已修改，请重新开始 / VAD changed; start again')};$('segmentStatus').textContent=$('vadMode').value==='semantic'?'Semantic VAD + merge':'Server VAD + merge'};$('classTitle').oninput=()=>{clearTimeout(state.titleTimer);state.titleTimer=setTimeout(saveSessionMeta,700)};$('accountButton').onclick=()=>{$('accountPopover').hidden=!$('accountPopover').hidden};$('logoutButton').onclick=async()=>{stopBeta();await supabase.auth.signOut();state.user=null;state.sessionId=null;state.entries=[];$('accountPopover').hidden=true;await enterApp(null)};window.addEventListener('online',retryPendingUploads);window.addEventListener('beforeunload',()=>{try{state.recognition?.stop()}catch{};cleanupRealtime()});supabase.auth.onAuthStateChange((_e,session)=>{if(session?.user?.id!==state.user?.id)enterApp(session)});const {data:{session}}=await supabase.auth.getSession();await enterApp(session);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})
